### ISSUE TITLE
CAPABILITY in wellcome-string from outlook.office365.com

### ISSUE THREAD

**Issue by warlin1** [simonrob/email-oauth2-proxy#109]
Good evening Simon Robinson, I would appreciate your reply.

An error occurs when trying to connect a proprietary IMAP-client to email-oauth2-proxy. 

> 2022-12-14 20:12:55,130: IMAP (localhost:1993; 127.0.0.1:53924->outlook.office365.com:993)     <-- b'* OK The Microsoft Exchange IMAP4 service is ready. [RgBSADIAUAAyADgAMQBDAEEAMAAxADIAMgAuAEQARQBVAFAAMgA4ADEALgBQAFIATwBEAC4ATwBVAFQATABPAE8ASwAuAEMATwBNAA==]\r\n'
2022-12-14 20:12:55,130: IMAP (localhost:1993; 127.0.0.1:53924->outlook.office365.com:993) <-- b'* OK The Microsoft Exchange IMAP4 service is ready. [RgBSADIAUAAyADgAMQBDAEEAMAAxADIAMgAuAEQARQBVAFAAMgA4ADEALgBQAFIATwBEAC4ATwBVAFQATABPAE8ASwAuAEMATwBNAA==]\r\n'
2022-12-14 20:12:55,132: IMAP (localhost:1993; 127.0.0.1:53924->outlook.office365.com:993) --> b'0001 LOGOUT\r\n'

The following wellcome-string comes from the outlook.office365.com server, after which the client immediately drops the connection (by LOGOUT command). I see in the client's logs that it cannot find a suitable authentication method

> fail to login: No supported authentication schemes available: Server supports (), client supports ['PLAIN', 'LOGIN']

By analysing the behaviour, I found that the client expects CAPABILITY in the welcome string from the IMAP server, e.g.
> * OK The Microsoft Exchange IMAP4 service is ready. [CAPABILITY IMAP4REV1 AUTH=PLAIN]\r\n

The thing is, this IMAP client, works correctly directly with outlook.office365.com via IMAP with authentication method LOGIN/PLAIN through SSL, so I think the error lies exactly in the blind transmission of the welcome-string from outlook.office365.com to the client.

Unfortunately, I have not found in the documentation how wellcome-string can be affected. It is not possible to make changes to the wellcome-string using the receive_from_client, receive_from_server plugin methods because these methods work after authentication. The only solution I've found is to change the byte_data in the handle_read function of the OAuth2ServerConnection class, but this is too messy!
Also I cannot understand according to rfc when connecting without SSL, the wellcome string must contain CAPABILITY 
indicating authentication methods, e.g. AUTH=PLAIN, but I would like to be able to force CAPABILITY to be added to the wellcome-string for such IMAP-clients.

P.S. For example, DavMail does not pass the uplink IMAP-server string, but welcomes its own: 
> * OK [CAPABILITY IMAP4REV1 AUTH=LOGIN MOVE SPECIAL-USE] IMAP4rev1 DavMail 6.0.1-trunk server ready

**Comment by simonrob** [comment]
The proxy currently doesn't identify itself or allow any customisation of the server greeting. It looks like your client isn't actually sending a `CAPABILITY` request here, which is why it doesn't get a response.

Where are you seeing that the `CAPABILITY` string should be provided in the server greeting? I can't see this in [RFC 3501](https://www.rfc-editor.org/rfc/rfc3501) (IMAP 4rev1) or [RFC 9051](https://www.ietf.org/rfc/rfc9051.html) (IMAP 4rev2). As you note, this is simply passed through directly from Office 365, so I'm not sure how your client works directly but fails with the proxy.

Please could you provide more details.

**Comment by warlin1** [comment]
> Does the imap rfc really say servers can return the capabilities in the greeting?
> 
> Yes its part of RFC3501 (7.1.) which clearly says:
> "Status responses MAY include an OPTIONAL "response code".  A response code consists of data inside square brackets in the form of an atom, possibly followed by a space and arguments."

I checked the source code of this IMAP-client, in the case of an SSL connection the client explicitly asks for CAPABILITY, but in the absence of SSL and CAPABILITY in the greeting the client drops the connection. I see that according to RFC3501 it is indeed possible to send CAPABILITY immediately in the greeting, but there is no strict requirement to do so. Based on this I think the problem is in the client side logic. 

But regardless of that, I think that the ability to spoof the greeting, e.g. via a plugin would be a good idea.

**Comment by simonrob** [comment]
Thanks for clarifying – you are right that RFC 3501 [does permit this method of providing capabilities](https://www.rfc-editor.org/rfc/rfc3501.html#section-7.1), but it doesn't say anything about whether it is required or not when connecting without SSL.

At connection time the proxy doesn't know anything about the underlying server's capabilities unless they are provided in the greeting – if they are not present it could only add in its own `AUTH=PLAIN` in addition to the required `IMAP4` (with an unknown revision). As an aside, I don't think the `AUTH=LOGIN` shown in your DavMail example is a valid capability; this is actually specified by not having `LOGINDISABLED` present. In addition, the reason that DavMail does not pass an upstream IMAP greeting is because there isn't one – DavMail is translating Exchange API calls to provide its own local IMAP server.

Servers that have this capability greeting behaviour should still work with the proxy detecting and modifying their capability response. Office 365 does not do this, so it is not possible to provide a comprehensive and accurate capability response until the server itself sends one.

I do see the benefit of having plugins available earlier in the connection, particularly for the `CAPABILITY` response (and similar for POP3's `CAPA` and SMTP's `EHLO`), but this would have to be balanced against the challenge of isolating them from the authentication steps. I do not want plugins to be able to intercept or modify anything to do with credentials.

**Comment by warlin1** [comment]
In fact, I first modified the handle_read function and achieved the desired behaviour of the IMAP client. but after analysing the IMAP client code, I plugged in a certificate and the problem was solved without the questionable modification of the handle_read function.

So thank you very much, for your help in solving the problem. Good luck in developing your project.

I would also like to add that I had to write oauth2-smtp-proxy myself before, in order to allow legacy devices to use a modern authentication method, with no-gui being the main requirement.
So the ability to initially retrieve access_token and refresh_token for the new mailbox I implemented with the built-in web server. When logging into this web server, a string was generated and redirected to the URL https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/authorize. After interactive authentication by the mailbox owner, a code was returned to callback_uri (web-server), which was used to retrieve access_token & refresh_token. This eliminated the need to use a GUI to retrieve the tokens. 
This seems to me to be a very convenient way for servers without a GUI.

**Comment by simonrob** [comment]
Interesting to hear about other solutions people have developed to resolve the OAuth email issue – it sounds like you settled on a similar approach to what the proxy's `--no-gui` option permits.

I'm glad you managed to find a way around this without resorting to modifying the proxy. Regardless, I may well move plugins earlier in the process on the server side (but not the client side) so that this sort of behaviour could be modified. This would also mean that other capabilities could be added or removed, which is a useful ability. Happy to be of help.

**Comment by simonrob** [comment]
I've just added the capability to intercept server messages before authentication, which enables more sophisticated plugins (e.g., the new examples in the [plugins branch](https://github.com/simonrob/email-oauth2-proxy/tree/plugins)), including the ability to use them to address the use-case you suggested above. Thanks for the prompt to look at this!

**Comment by warlin1** [comment]
Thank you for the new functionality. You are a very responsive developer, very nice.
