### ISSUE TITLE
Initial authorization

### ISSUE THREAD

**Issue by 0geronimo0** [simonrob/email-oauth2-proxy#124]
Hello @simonrob ,

thank you very much for the contribution. I am using Debian server without GUI and I am trying to set proxy for SMTP and IMAP. 

First: suggestion
- I've spent some time looking at the errors while starting py script and at the end I figured it out I need to install Python 3 and run script with explicit python3 command

Second: Authorization error
- I've managed to start the proxy which is listening to request
- I've reconfigured my e-mail service to use port 1587 and localhost (for SMTP)
- when I try to send e-mail I get error message in my e-mail service "An error occurred while sending mail (535 5.7.8 Authentication credentials invalid. Email OAuth 2.0 Proxy: Login failed for account XXXX@YYYY.com - please check your internet connection and retry )"
- this error is understandable as I haven't done initial authorization
- I tried to run script with --external-auth --no-gui and --local-server-auth --no-gui but in both cases I get proxy error "Caught exception while requesting OAuth 2.0 credentials for XXXX@YYYY.com: {'error': 'unsupported_grant_type', 'error_description': "AADSTS70003: The app requested an unsupported grant type 'XXXX@YYYY.com'.\r\nTrace ID: xxxxx\r\nCorrelation ID: xxxxxx\r\nTimestamp: 2023-01-18 23:53:27Z", 'error_codes': [70003], 'timestamp': '2023-01-18 23:53:27Z', 'trace_id': 'XXXX', 'correlation_id': 'XXXXX'}"

Can you please share what I am doing wrong? I've red all documentation and other support cases but cannot find the cause.

Thank you in advance.

**Comment by simonrob** [comment]
> * run script with explicit python3 command

The [readme](https://github.com/simonrob/email-oauth2-proxy#dependencies-and-setup) does already mention the need to use Python 3.6 or later. `python3` is normally just an alias of `python`.


> * 'error': 'unsupported_grant_type', 'error_description': "AADSTS70003: The app requested an unsupported grant type

This is the root of the issue you are encountering, and is because your O365 configuration either does not support or is not set up properly for the OAuth flow you are requesting. It is best to start with the [default configuration](https://github.com/simonrob/email-oauth2-proxy/blob/a26edc6e1370f399894059c1fe96beee666eda7a/emailproxy.config#L136) first before trying more advanced setups.

**Comment by 0geronimo0** [comment]
> It is best to start with the [default configuration](https://github.com/simonrob/email-oauth2-proxy/blob/a26edc6e1370f399894059c1fe96beee666eda7a/emailproxy.config#L136) first

I've tried with default configuration but got the same error. I'll check O365 configuration once again and get back with results.

**Comment by 0geronimo0** [comment]
I got it working! Thank you very much Simon
