### ISSUE TITLE
"Start at login" produces error for standalone executable on Windows 10

### ISSUE THREAD

**Issue by bwbug** [simonrob/email-oauth2-proxy#135]
When selecting the "Start at login" option in the systray icon produced by a standalone executable compiled for Windows 10 produces the error message `Windows cannot find `C:\Program`.

The .cmd file in the startup folder contains the following command \[slightly redacted\]:

```
start C:\Program Executables\Email-OAuth2-Proxy\dist\emailproxy.exe C:\Users\username\AppData\Local\Temp\_MEI134122\emailproxy.py
```

I believe I can fix the error by making the first argument `C:\progra~4\Email-OAuth2-Proxy\dist\emailproxy.exe`, or perhaps by enclosing it in double-quotation marks, but perhaps it would make sense to check for spaces in the path when generating the expression.

Would you mind explaining the reason/purpose for the second argument (`C:\Users\username\AppData\Local\Temp\_MEI134122\emailproxy.py`)?  Can this be omitted if I want to set up my own startup script?

**Comment by simonrob** [comment]
Thanks for reporting this. There are two issues here – firstly, the lack of consideration of spaces in file paths when using the `Start at login` option. Start at login is a bit of a bonus feature, and actually surprisingly hard to get right on all platforms. c1a78de fixes this, though it may well be possible to carefully craft file names or other parameters to break it. The assumption here is that users of the proxy won't try to break their own systems. I don't actually have access to Windows to test this, but it _should_ work.

The second issue is that the script should not try to include its own path when packaged via PyInstaller, as this is built into the executable. This is also fixed in c1a78de.

**Comment by simonrob** [comment]
Yes - that's the second fix mentioned above. In normal mode (without PyInstaller) this is the path to the proxy script, but that is not needed when compiled into a single file.

**Comment by simonrob** [comment]
I'm going to close this issue since from my own testing this has been resolved. Feel free to reopen if that is not the case for you.

**Comment by simonrob** [comment]
Thanks for checking. The initial pair of double quotes is intended - it's for specifying the title of the command prompt window, but because it is running in windowless mode no title is needed (though the quotes are still mandatory).
