### ISSUE TITLE
Do tokens expire?

### ISSUE THREAD

**Issue by xrisk** [simonrob/email-oauth2-proxy#173]
Hi! Thanks for your work on this great piece of software.

There is a recurring issue I’m facing: every 2-ish months, I need to re-authenticate with my password to O365. I’m assuming that the tokens are expiring. Is this how OAuth2 tokens are expected to behave? If not, is this something else I’m running into?

Here is a relevant snippet from my logs:

```
Jun 12 23:42:46 xxx python[1234]: Email OAuth 2.0 Proxy: IMAP (localhost:1993; xxx) [ Successfully authenticated IMAP connection - releasing session ]
Jun 12 23:43:47 xxx python[1234]: Email OAuth 2.0 Proxy: IMAP (localhost:1993; xxx) [ Successfully authenticated IMAP connection - releasing session ]
Jun 12 23:44:48 xxx python[1234]: Email OAuth 2.0 Proxy: IMAP (localhost:1993; xxx) [ Successfully authenticated IMAP connection - releasing session ]
Jun 13 00:16:18 xxx python[1234]: Email OAuth 2.0 Proxy: IMAP (localhost:1993) Caught network error (server) - is there a network connection? Error type <class 'ConnectionResetError'> with message: [Errno 104] Connection reset by peer
Jun 13 05:00:04 xxx python[1234]: Email OAuth 2.0 Proxy: Retrying login due to exception while requesting OAuth 2.0 credentials for xxx: InvalidToken(400, 'ac.robinson.email-oauth2-proxy')
Jun 13 05:00:04 xxx python[1234]: Email OAuth 2.0 Proxy: Authorisation request received for xxx (interactive mode)
Jun 13 05:10:04 xxx python[1234]: Email OAuth 2.0 Proxy: Authorisation result error for xxx - aborting login. Authorisation request timed out
Jun 13 05:10:07 xxx python[1234]: Email OAuth 2.0 Proxy: Authorisation request received for xxx (interactive mode)
Jun 13 05:20:07 xxx python[1234]: Email OAuth 2.0 Proxy: Authorisation result error for xxx - aborting login. Authorisation request timed out
```

(I have a cronjob that runs a email script every minute)

I’m running the version from 2022-12-23, although I believe I cloned it from master so it might not be the release version.

**Comment by simonrob** [comment]
Yes, it is normal for access tokens to expire. Two months does seem a bit more often than I'd expect, but it may be that your particular O365 setup has been configured to require this.

**Comment by xrisk** [comment]
Thanks for the your reply. However, as far as I understand from references like [3], [1] and [2]: as long as the refresh token is used within a period of 90 days and a new refresh token is obtained, we should never be required to re-authenticate again.

 Can you confirm how frequently the refresh token is being renewed?

**Comment by simonrob** [comment]
The [AAD token lifetime documentation](https://learn.microsoft.com/en-us/azure/active-directory-b2c/configure-tokens?) explains the different parameters that apply here. I'd recommend checking your AAD configuration to see whether the lifetime length is set to have a specific number of days before expiry.

Prior to [this commit](https://github.com/simonrob/email-oauth2-proxy/commit/f892aa1003890db9da3529689cbff49583d28214) the proxy did not always renew the refresh token, so might have prematurely hit the token lifetime (rather than the overall lifetime length), but given that you have said you are using 2022-12-23 this will not be the case. I'd still recommend updating, however, as more recent versions give more detail, including the error message received when the token has been rejected, which may help you isolate the reason behind this.

The token is only ever discarded when its given expiry date is reached or it is rejected by the server during account authorisation.

**Comment by simonrob** [comment]
I'm going to close this given that this is simply a configurable behaviour of AAD. Feel free to re-open if you find a related issue with the proxy.
