### ISSUE TITLE
The menu bar icon doesn't update its content when an IMAP account is added using a catch-all configuration

### ISSUE THREAD

**Issue by Draykan** [simonrob/email-oauth2-proxy#175]
I use Email OAuth 2.0 Proxy to access Office 365 mailboxes with IMAP using Apple Mail on Mac.
I noticed that when an IMAP account is configured and authenticated using a catch-all configuration, it is not added to the Menu bar icon --> Servers and account --> Accounts list until the proxy is restarted.
This doesn't happen with a straight IMAP account configuration.
I didn't test on other platforms.

System information and software versions:
• MacBook Air (M1, 2020)
• macOS Ventura 13.5 (22G5048d) Beta 3
• Command Line Tools for Xcode 14.3 (installed for the first time on 04/04/2023 and according to System Information app updated to the same version on 06/06/2023 with Software Update)

`python3 emailproxy.py --version`
```
Email OAuth 2.0 Proxy 2023-05-18
```

`python3 --version`
```
Python 3.9.6
```

`python3 -m pip list`
```
Package                              Version
------------------------------------ -------
altgraph                             0.17.2
bottle                               0.12.25
cffi                                 1.15.1
cryptography                         41.0.1
future                               0.18.2
macholib                             1.15.2
Pillow                               9.5.0
pip                                  21.2.4
prompt-toolkit                       3.0.38
proxy-tools                          0.1.0
pycparser                            2.21
pyobjc-core                          9.2
pyobjc-framework-Cocoa               9.2
pyobjc-framework-Quartz              9.2
pyobjc-framework-Security            9.2
pyobjc-framework-SystemConfiguration 9.2
pyobjc-framework-WebKit              9.2
pyoslog                              1.1.0
pystray                              0.19.4
pywebview                            4.2.1
setuptools                           58.0.4
six                                  1.15.0
timeago                              1.0.16
typing_extensions                    4.6.3
wcwidth                              0.2.6
wheel                                0.37.0
WARNING: You are using pip version 21.2.4; however, version 23.1.2 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
```

**Comment by simonrob** [comment]
Please could you clarify the behaviour you're seeing vs. what you're expecting to see? I think this might be confusion between the standard behaviour and the catch-all account feature.

Whenever you add a new account of any type manually, you'll need to either restart the proxy or use the `Reload configuration file` menu option to signal that you've made a change. The proxy doesn't monitor the configuration file in any way.

New accounts that are covered by an existing catch-all filter can appear in the menu bar interface without reloading or restarting because the proxy is itself adding these to the configuration file when they are first successfully authenticated.

Finally, while the proxy force-refreshes the menu bar account list after every successful authentication (and with macOS is even more proactive about this), if you actually click the `Servers and accounts` menu heading rather than just hovering over it this will also force a menu refresh.

**Comment by Draykan** [comment]
Hi Simon,
I'm pointing out that actually this is not working:
_"New accounts that are covered by an existing catch-all filter can appear in the menu bar interface without reloading or restarting because the proxy is itself adding these to the configuration file when they are first successfully authenticated."_

After authenticating a new account, the menu bar is still like this:
<img width="686" alt="After authenticating a new account" src="https://github.com/simonrob/email-oauth2-proxy/assets/151580/358a9499-4d14-425f-beed-db3b623da76b">

After clicking on `Servers and accounts`, the new account appears:
<img width="683" alt="After authenticating a new account and clicking on  Servers and accounts" src="https://github.com/simonrob/email-oauth2-proxy/assets/151580/fbeff3b9-1334-48f5-9f20-580d8279df46">

**Comment by simonrob** [comment]
Ah, thanks for clarifying – I see what you mean now. This is happening because catch-all accounts are treated slightly differently, and the new account is only added to the configuration file after the GUI is refreshed. I'll think about whether this can be improved in a future version.
