### ISSUE TITLE
AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access

### ISSUE THREAD

**Issue by brianjmurrell** [simonrob/email-oauth2-proxy#181]
When I try to authorize the proxy I get the following error:

```
python3[1644933]: Email OAuth 2.0 Proxy: Caught exception while requesting OAuth 2.0 credentials for [redacted]: {'error': 'invalid_grant', 'error_description': 'AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2023-06-02T14:27:05.8405153Z and the maximum allowed lifetime for this request is 86400.\r\nTrace ID: [redacted]\r\nCorrelation ID: [redacted]\r\nTimestamp: 2023-07-06 13:35:42Z', 'error_codes': [70043], 'timestamp': '2023-07-06 13:35:42Z', 'trace_id': '[redacted]', 'correlation_id': '[redacted]', 'suberror': 'token_expired'}
```

What I find odd however is that I thought the refresh token was stored in the file pointed to by the `--cache-store` argument when starting the proxy.  My proxy has the arguments: `--cache-store /home/brian/.config/ac.robinson.email-oauth2-proxy/config --debug` and `/home/brian/.config/ac.robinson.email-oauth2-proxy/config` doesn't even exist so where would a stale refresh token be coming from?

**Comment by simonrob** [comment]
That's an error I haven't seen before. Is this an account that you have previously authorised successfully? The reason I ask is that the proxy doesn't cache anything until authorisation is successful, so if this is the first use then the file may not yet exist.

If that is not the case, the only other place the token could be is the main proxy config file (i.e., the default behaviour). If this is happening then there's likely a bug – the proxy is intended to fail to save and print an error, rather than falling back to the main config file. Is there any more information you can share?

**Comment by simonrob** [comment]
I'm going to assume that this was resolved, and will close the issue given that I cant replicate this. However, please feel free to reopen if that's not the case.

**Comment by brianjmurrell** [comment]
Yes, I had previously successfully authorized this account.  But I did, in the efforts of debugging this issue, rename the existing `/home/brian/.config/ac.robinson.email-oauth2-proxy/config{,.old}`.

But this issue does continue to persist.

**Comment by simonrob** [comment]
Were you able to find out any more about why this might be happening?

**Comment by brianjmurrell** [comment]
Not really.  I suspect this was just more of the corporate VPN/proxy/source-ip restriction palaver.

I'll close until it happens again with no remedy.
