### ISSUE TITLE
Duplicate email received

### ISSUE THREAD

**Issue by t0m31** [simonrob/email-oauth2-proxy#188]
Hi, 

I am using Oauth Proxy Server with Axigen, configured 4 accounts (all Office 365). However, got one account having issues and receiving duplicate emails. 

After remove that user from Axigen and add back (re-authenticate the Oauth) the issues gone. But after few days, the issues come back again. 

Any ideas to fix it? Thanks

**Comment by simonrob** [comment]
This is unusual, but I'm afraid it is a client issue rather than anything to do with the proxy. 

(The standard version of the proxy could not do anything to cause this, because it removes itself after authentication; the plugins branch could potentially do this via a misconfigured plugin, but I'm assuming that you're not doing that.)
