### ISSUE TITLE
Latest release 2023-12-19 reports wrong version number

### ISSUE THREAD

**Issue by Profex** [simonrob/email-oauth2-proxy#218]
Many thanks for fixing the security issue with CCG in latest version!

Just a small remark, latest script version reports wrong version number when starting the script
The proxy reports "2023-11-19", while it should be "2023-**12**-19"

**Comment by simonrob** [comment]
Thanks – this was also pointed out in #216. It's not a problem except for the potential for confusion, so rather than add to this by reverting and re-releasing, I'll leave this issue open for now and also make a note on the release.

I've added a [pre-commit hook](https://github.com/simonrob/check-iso8601-version-string/) to make sure this doesn't happen again.

**Comment by Profex** [comment]
Thanks for getting back, overlooked that this was already reported in https://github.com/simonrob/email-oauth2-proxy/issues/216
