### ISSUE TITLE
Thunderbird Client ID no longer works?

### ISSUE THREAD

**Issue by bwbug** [simonrob/email-oauth2-proxy#267]
For one of my Office 365 email accounts, I can no longer authenticate using the proxy (using the Thunderbird Client ID).

I realize that this might technically not be an issue with email-oauth2-proxy  _per se_, but the Thunderbird Client ID is still referenced in your [README](https://github.com/simonrob/email-oauth2-proxy/blob/785f6152428c58aed46b9d0d519b7e59f0ae5c43/README.md?plain=1#L64), and you did indicate [as recently as July 4](https://github.com/simonrob/email-oauth2-proxy/issues/259#issuecomment-2209527873) that the new Thunderbird client ID worked for authenticating with the proxy, so I'm hoping that you will be willing/able to provide some assistance.

When using the older Client ID for Thunderbird (`08162f7c-0fd2-4200-a84a-f25a4db0b584`) and the corresponding Client Secret, I now (as of Aug. 1) get the following error message:

>Message: AADSTS7000112: Application '08162f7c-0fd2-4200-a84a-f25a4db0b584'(Thunderbird) is disabled.

When I changed the Client ID to `9e5f94bc-e8a4-4e73-b8be-63364c29d753` and removed the Client Secret (and also updated the `oauth2_scope` as specified [here](https://learn.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth#get-an-access-token)), I now get the following error message instead:

>Message: AADSTS50011: The redirect URI 'http://localhost' specified in the request does not match the redirect URIs configured for the application '9e5f94bc-e8a4-4e73-b8be-63364c29d753'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.

In both cases, the authentication ceremony appears to complete successfully (with a "Success" message in the browser) before the error message is triggered upon redirect.

Can you confirm that you are still able to use the email-oauth2-proxy with a Thunderbird Client ID to authenticate to an Office 365 or Microsoftonline account, and if so provide some assistance with troubleshooting my set-up?

Thank you!

**Comment by simonrob** [comment]
Thanks for the pointer to the new Thunderbird file – I'll link to this.

Re: the two different configuration file examples – I've kept both of these here because for me, both Thunderbird IDs still work. Perhaps an administrator on your side has disabled the older ID?

**Comment by simonrob** [comment]
The honest answer is that many of the values in the configuration file have been discovered through trial and error, support requests or following other clients' examples, because historically documentation has been quite lacking.

The scope values in the Microsoft documentation were [last updated in 2020](https://github.com/MicrosoftDocs/office-developer-exchange-docs/commit/9d5d6b8eac0e9ea3d2b1525c735baf11eadd6817), but Thunderbird only [updated to match these](https://github.com/mozilla/releases-comm-central/commit/9928839e0c4686ae45939f416d64ce15ac113113#diff-c2e4ec4b5a9f95c8d995849fc17f3118d45a39bfc3131112e4cab32973c81d6d) in 2022. Microsoft's documentation still uses the `office365.com` versions [in examples elsewhere](https://learn.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-authenticate-an-ews-application-by-using-oauth), and O365 also requires this in certain configurations (e.g., the `.default` scope that is used for CCG, etc).

Since the newer scope values work with both the old and new Thunderbird IDs, I think it's relatively safe to presume they are treated as aliases for each other. The additional example here was only added recently to cover a case where the older scopes didn't work, so I'll go ahead and remove the old ones to lessen the confusion.

**Comment by simonrob** [comment]
I did check both Thunderbird IDs, and they work fine with the new scopes, which is why I've [switched this over](https://github.com/simonrob/email-oauth2-proxy/commit/32865aefb2cf9be2d8e28171d8f89c016592958f). The example configuration file is meant to show the setup required, but reuse of other clients' secrets is a bit of a grey area, so I tend to stick to the officially documented values unless lots of issues are being caused.

The file does already [discuss the `redirect_uri` value](https://github.com/simonrob/email-oauth2-proxy/blob/32865aefb2cf9be2d8e28171d8f89c016592958f/emailproxy.config#L177) and the need for it to match what is specified in the OAuth 2.0 client configuration. Fortunately, the error messages from most providers are pretty helpful here, and normally tell you what the correct value needs to be.

Thanks again for pointing this out – glad you were able to figure out the root cause.

**Comment by merbanan** [comment]
> and trying `https://localhost` in the `redirect_uri` parameter (if `http://localhost` does not work).

This worked for me. Would be nice if it was in the docs.

**Comment by simonrob** [comment]
[This](https://github.com/simonrob/email-oauth2-proxy/blob/3ed7dfdcd1d7a9dc2a392aecaae7bb5d913acec0/emailproxy.config#L195) is the relevant section of the example configuration, noting that `http://localhost` is the most common, but not ruling out other values. If you choose to reuse a secret it's best to just check your source to find the correct value – see the [link above](https://hg.mozilla.org/releases/comm-esr102/rev/37f32ce1863b#l6.131).
