### ISSUE TITLE
not valid creditentials

### ISSUE THREAD

**Issue by petereonhombolygo** [simonrob/email-oauth2-proxy#279]
Hello.

I tried to implement the solution. In my windows machine, i can join to the mail server, and possible to read out the emails from my mail server. Everything works perfectly.

My config file looks like this:

[xxxxxxxx]
permission_url = https://login.microsoftonline.com/ccccccccccccc/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/cccccccccccccc/oauth2/v2.0/token
oauth2_scope = https://outlook.office.com/IMAP.AccessAsUser.All https://outlook.office.com/SMTP.Send offline_access
redirect_uri = vvvvvvvvvv
client_id = bbbbbbbbbb
client_secret = sssssssss
last_activity = 1725977826
token_salt = aaaaaaaaa
token_iterations = 870000
access_token = tttttttttttttt
access_token_expiry = 1725982550
refresh_token = rrrrrrrrrrrrr

But when i want to use it in my non-gui ubuntu environment, i can just copy-paste the entire config file to the server, start the process, and when i try to authenticate, i got an error as "InvalidToken", and try to open the interactive mode. (But as a non-gui operation system, its imposible).

And after this, i tried out in my windows machine again, and it working perfectly. The credentials works, no need to log-in again.

Is there a good way to copy my config file from windows to ubuntu?

**Comment by simonrob** [comment]
Please read the full error message that is produced when you see the `InvalidToken` error. The reason is that you are using a different email client password in your Ubuntu and Windows environments.

Because the proxy encrypts the stored credentials, if you copy the configuration to a new environment you will also need to use the same password in that email client. Note that this does not need to be your real account password – see the [readme](https://github.com/simonrob/email-oauth2-proxy?tab=readme-ov-file#troubleshooting) for more explanation about this.
