### ISSUE TITLE
GUI doesn't works 

### ISSUE THREAD

**Issue by cacoch** [simonrob/email-oauth2-proxy#28]
I'm using I3wm. GUI doens't works. 
`python emailproxy.py  --debug --no-gui --local-server-auth` works  for me fine. 

####
Great idea, great job. I was looking exactly for this. Thanks

**Comment by simonrob** [comment]
Available GUIs are reliant on [pystray](https://github.com/moses-palmer/pystray), and it looks like it doesn't currently support I3wm. Hopefully the no-GUI option works well for you. I'm glad the proxy is useful!

**Comment by codewinch** [comment]
i3 doesn't have a system tray configured by default:

https://i3wm.org/docs/userguide.html#_tray_output

If it is set up properly, then you should be able to see the icons from apps that offer them.

(This might be a problem with many lightweight DE's that don't use system trays by default - wonder if it'd be possible to open up the GUI with `--gui`?)

**Comment by Konfekt** [comment]
> (This might be a problem with many lightweight DE's that don't use system trays by default - wonder if it'd be possible to open up the GUI with --gui?)

Maybe it could be added to the Readme / FAQ that the GUI is supposed to work on Gnome and Ubuntu (according to the linked https://github.com/moses-palmer/pystray/ readme), but maybe something like a systemd service is preferable on other desktop envirionments.

> What might be useful is having an option that causes the proxy to call, e.g., xdg-open [authentication link] whenever a request is received in --local-server-auth mode. Would that work?

Yes, that would help. Since emailproxy by default starts a tray, intended users are likely using it inside a desktop environment. Without a tray, it's likely running in background and its output could be hidden. 

Opening the URL, instead of printing it on the terminal, is also what other oauth2 tools opted for, say https://github.com/harishkrupo/oauth2ms/

**Comment by Konfekt** [comment]
Maybe it could also be explained what is done on expired certificates without a tray icon but using a desktop environment.  From reading https://github.com/simonrob/email-oauth2-proxy/?tab=readme-ov-file#optional-arguments-and-configuration one gets the impression that the output should be surveyed for authentication links to be pasted into the browser's address bar.

Finally, regarding

> After visiting the link provided and authorising account access, paste the final URL from your browser's address bar back into the proxy's popup window (GUI mode) or the terminal (no-GUI mode) to give it access to transparently proxy your login.

as a user one might wonder about the advantage of using `--external-auth` instead of `--local-server-auth`; it seems more manual interaction is required.
