### ISSUE TITLE
Is there any clues to use with fetchmail

### ISSUE THREAD

**Issue by libtantang** [simonrob/email-oauth2-proxy#300]
Can I use this proxy with fetchmail?I did not find description on how to use it with fetchmail.

Thanks in advance.

**Comment by simonrob** [comment]
You can use the proxy with anything that can use the IMAP/POP/SMTP protocols. If you search previous issues you'll see a [few previous discussions that mention fetchmail](https://github.com/simonrob/email-oauth2-proxy/issues?q=is%3Aissue+fetchmail).

In future, for support requests it's better to use [Discussions](https://github.com/simonrob/email-oauth2-proxy/discussions) rather than opening issues (which are more for bug reports).
