### ISSUE TITLE
Option for manual authorisation

### ISSUE THREAD

**Issue by john-at-charpa** [simonrob/email-oauth2-proxy#5]
Greetings, 

For some time I've been looking for a way to use (X)OAUTH2 with an 'ancient' email client and my organisations O365 instance. Unfortunately? we also employ SSO via a fairly well known provider. Due to this extra layer of redirects most scripts or applications (like this one) get fairly confused and simply fail. This is the case with Davmail, too. However, because Davmail provides an option for manual authentication, the initial authentication and token exchange can be done by via cut & paste in a full blown browser. 

Would it be possible to add a non-GUI or option in the GUI for manual token/URI entry? This would solve the issue I have now with the http(s) client used by email-oauth2-proxy becoming confused by SSO twisty tunnels of pain. Currently it starts the authentication as one would expect, but after an email address is entered the user is presented with a blank white screen (the same issue happens with Davmail). 

I have also successfully used the mutt OAUTH2 python script to get an initial token, but the encryption and storage method (which uses gpg2 to store the token data) differs from your script and therefore cannot be used (unless I could see an example and manually encrypt and insert into the configuration. https://gitlab.com/muttmua/mutt/-/blob/master/contrib/mutt_oauth2.py

Is there some way to override/manually authenticate in the current codebase?

**Comment by simonrob** [comment]
Thanks for this suggestion. I'm quite interested in why the SSO process fails in your case - perhaps it is redirected via some local/internal page that confuses the script? It may not be solvable (or indeed worth setup-specific code to do this), but I'm curious that neither DavMail nor this script can cope with it. I can't remember how DavMail handles login, but here the login popup is simply a [pywebview](https://github.com/r0x0r/pywebview/), which should just be a normal browser component. Let me know if you find out what is happening here?

I had a quick look at the mutt OAuth script, and decided that since compatibility with that would require GPG to be present (which is not the case across different platforms) it would be best to try another way.

Could you try the version in the [manual-auth](https://github.com/simonrob/email-oauth2-proxy/tree/manual-auth) branch and see whether this works for you?

It should still pop up a window as normal for authentication, but instead of navigating to the `permission_url` itself, this version displays it and asks you for the result. You may note that there's a new `--manual-auth` parameter, but this is currently set to default in this branch so you shouldn't need to change anything about your configuration; just drop in the new `emailproxy.py`.

**Comment by john-at-charpa** [comment]
Simon, 

Thank you for the follow up. The mutt script's GPG is a nice touch, but it does certainly add to the already ludicrous complexity of (x)oauth2/oauthbearer (and adds yet another pop-up..). 

I switched to the manual-auth branch and gave it a try. It pops up a different window and the URL is valid, but after pasting the URL from the web browser into the box the submit button does nothing. I've tried both the entire URL as well as the 'code' segment with https://localhost removed. I ran with --debug but nothing is logged after: Email OAuth 2.0 Proxy: Authorisation request received for XXX. I did verify all the dependencies are met (this is macOS); I assume if they weren't I'd be getting python errors anyway.

**Comment by simonrob** [comment]
Interesting - I wonder whether you're also running up against the [known issue](https://github.com/simonrob/email-oauth2-proxy#known-issues) where pywebview gets into a "stuck" state and cannot navigate to local URLs? A system restart fixes this, and is worth a try.

I notice you quoted the URL as starting with `https://`. Normally this is actually `http://` (i.e., not secure), and it is important for this `redirect_uri` parameter to be correct in `emailproxy.config` as this is what the script looks for to see whether authorisation has completed. Can you check?

I haven't tried with a configuration that uses a secure redirection as that would probably fail everywhere due to not having a HTTPS certificate. If this really is the correct result then I think a very different approach will be needed (i.e., without the webview at all, and some refactoring and inclusion of a GUI toolkit, which I'm a little reluctant to do)

**Comment by john-at-charpa** [comment]
So, I've given it another go today. I had way too many projects open on Friday to reboot, so I ran through it again after rebooting (I had put off a few macOS updates anyway). The same thing happened again, but you were certainly correct about the url being http://localhost and not https:// -  likely just a force of habit typo on my part. I did also make sure the VPN was disconnected to ensure that it wasn't blocking inbound (or even localhost) connections.

I should mention that you can change the GPG part of the mutt oauth script fairly simply. It's just a pipe, so the code at the top can be changed to pretty much anything (I used 'cat' during debug).  Unfortunately I've since found out that mutt's imap code quite dislikes O365 and it's fairly unusable (O365 throws errors and disconnects constantly). I'm curious to see if the proxy code in emailproxy.py makes it more reliable, but my guess is that only something like Dovecot running in caching mode would really be able shield mutt from the pain. 

I'll poke at this a bit more in the coming days to see if I can make any progress. I suspect that under normal circumstances the code works just fine and the twist tunnels of SSO redirects at my shop is to blame.

**Comment by simonrob** [comment]
Thanks for trying this again and reporting back. I was very curious about this issue, and couldn't understand how your SSO redirects would break things (unless they exactly matched the final authentication URL, but this would surely cause other problems), and also how you were encountering a similar redirection failure on macOS to one I've seen, but it wasn't fixed by a restart.

After looking at lots of different potential causes, I finally realised that because I sometimes have a local web server running when developing, this had been letting pywebview navigate to an actual localhost page without my knowledge, which allowed authentication to complete. It turns out that without the web server in place, pywebview has _never_ been able to actually resolve these authentication redirects on macOS. Ironically enough, concern about this sort of issue was the initial reason the script doesn't take mutt's approach of running its own web server to catch the account authorisation result.

The latest commit in the [manual-auth](https://github.com/simonrob/email-oauth2-proxy/tree/manual-auth) branch fixes this in all the situations I can test by extending pywebview's functionality on macOS. I've updated the script so that external browser-based authorisation is no-longer the default like it was last time you tried, but given that it was the redirection that was likely the problem you may actually find that you don't need this anyway. However, since I'd already added the code specific to that option, I've kept it in place, and you can enable it using `python3 emailproxy.py --external-auth`.

Please let me know how you get on. If possible, it would be great if you could try both the script's internal browser popup and the external browser-based authentication option.

Re: mutt and unreliability - this may because that script uses Python's own imaplib, which can be a little flaky. The email proxy  here can't use that method, but also has no interaction with the server beyond authentication, so is in my experience 100% reliable. I use O365 daily with it and have never encountered a problem, though please do of course report any issues you encounter.

**Comment by simonrob** [comment]
Just to update: I've merged the manual-auth branch because the redirection fix it includes should clearly be part of the script regardless of whether the external authentication part fixes your issue. Hopefully the main branch will now work for you.

Let me know if you do or don't manage to get things set up - I'm happy to take another look if you run into any more problems.

**Comment by john-at-charpa** [comment]
I've given it go this morning and you were correct on all points. It now works as expected. Many thanks for the fixes and assistance!

**Comment by simonrob** [comment]
Excellent! Thanks for identifying this; glad it is now resolved.
