### ISSUE TITLE
Doesnt do anything for me

### ISSUE THREAD

**Issue by JerryGeis** [simonrob/email-oauth2-proxy#76]
I downloaded for CentOS 7
did pip-3 install --upgrade pip
so cryto would install

changed my config

[IMAP-1993]
local_address = localhost
server_address = outlook.office365.com
server_port = 993

[POP-1995]
server_address = outlook.office365.com
server_port = 995

[SMTP-1587]
server_address = smtp.office365.com
server_port = 587
starttls = True

[abc@xyz.com]
permission_url = https://login.microsoftonline.com/common/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/common/oauth2/v2.0/token
oauth2_scope = https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/POP.AccessAsUser.All https://outlook.office365.com/SMTP.Send offline_access
redirect_uri = http://localhost
client_id = abc@xyz.com
client_secret = old_secret

I run the "python3 emailproxy.py --no-gui" even tried adding the --debug --debug 

all that prints is the start up of starting IMAP POP SMTP - nothing else - nothing about trying to connect to my user or anything?

What have missed in config ?

Thanks - sure hope I can get this working.

jerry

**Comment by JerryGeis** [comment]
It says...
Starting IMAP...
Starting POP...
Starting SMTP...
Iniitalization Email OATH2 proxy - listening.


I need it to go out and scrape that inbox I defined.
how do I do that?
Jerry

**Comment by simonrob** [comment]
The proxy will not automatically scrape your accounts or anything like that; instead, it acts as an intermediary between your existing email client and the remote OAuth 2.0 server.

Please take a look through the readme and set up your client to connect to the proxy instead of the IMAP/POP/SMTP server - you will then see a prompt about OAuth login and authorisation.
