### ISSUE TITLE
--no-gui and --external-auth support

### ISSUE THREAD

**Issue by jlevon** [simonrob/email-oauth2-proxy#94]
I'd like to run completely headless: if I need to re-auth for whatever reason, I'd like to use --external-auth, but via an interactive run (copy and paste on the terminal). This is like davmail headless mode.

I can't use --local-server-auth as the redirect_url must match the expected one for o365 (so localhost won't work).

Any thoughts?

**Comment by simonrob** [comment]
There has previously been [some discussion](https://github.com/simonrob/email-oauth2-proxy/issues/62#issuecomment-1247200491) about this type of usage, but it is not currently supported because it would need to either block the script or add extra complexity and potential for confusion (e.g., multiple accounts needing authentication simultaneously).

Why wouldn't you just update the `redirect_url`?

**Comment by jlevon** [comment]
Again, I can't update the redirect_url, it has to match a set of ones on the server.
In my case I want it to block the script, since I can't do anything with it until I'm authenticated. And if I'm not at the GUI, I'm blocked anyway since I can't access the systray.

**Comment by simonrob** [comment]
Of course, but what I meant is why not update the configuration of your O365 client to add `http://localhost` as an option?

**Comment by jlevon** [comment]
Oh, I think you're asking about the client corresponding to the client_id I'm using. That's because, as far as I was able to tell, I don't have permissions to register such a client that can access the O365 instance -  I can't remember what didn't work though.

So I'm re-using davmail's client_id. IIRC some oauth2 providers don't even let you register new clients *at all*.

(The whole "you have to create your own client_id" thing seems a bit of a bonkers part of oauth2 to me).

**Comment by simonrob** [comment]
In that case you have three main options, in order of preference:

1) Use a different client ID.

2) Set `redirect_uri` to the correct value and add `redirect_listen_address = http://localhost`. Outside of the proxy, map your `redirect_uri` to `127.0.0.1` (for example, via a hosts file edit), and then use `--local-server-auth` as normal.

3) Hack around this, replacing the contents of [this method](https://github.com/simonrob/email-oauth2-proxy/blob/803f3a85c90dc4302e37b55a62aefc8fd216eb41/emailproxy.py#L527) with something like the following (which I have not tested in any way), again making sure the `redirect_uri` value in your proxy configuration file matches what is expected:

```python
Log.info('Please visit the following URL to authenticate account %s: %s' %
         (token_request['username'], token_request['permission_url']))
token_request['response_url'] = input('Please paste the resulting redirection URL: ')
del token_request['local_server_auth']
RESPONSE_QUEUE.put(token_request)
```

**Comment by jlevon** [comment]
3) is exactly what I'm asking for - I'm not quite sure why it's a hack, as it's exactly how --external-auth does it right?

Would you take a PR that does this iff --no-gui + --external-auth?

**Comment by simonrob** [comment]
Not for this particularly hacky way of doing it - it is flawed and not suitable outside of this use-case.

I am happy to consider better ways to achieve this, but not anything that blocks the script or would conflict with log outputs.

**Comment by simonrob** [comment]
Thanks for the suggestion. I actually think this could add further confusion, because using `--no-gui` without `--local-server-auth` will similarly not raise any authentication prompts, but wouldn't (and shouldn't) be refused. In general, I think the readme makes it pretty clear that `--local-server-auth` is the only currently valid option to allow authorisation to work in non-GUI mode.

It is probably worth at some point consolidating the various authorisation options into a single parameter that defaults to interactive mode when a GUI is present, and some sort of stdin-based approach (for example, via [prompt_toolkit's patching](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/examples/prompts/patch-stdout.py)) when not. However, as explained above, I'm not open to any changes that block the proxy or interfere with log output from other threads – using with multiple accounts is very common, and there are lots of potential issues here.

**Comment by simonrob** [comment]
I had a look just now at whether the [`prompt_toolkit` approach](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/examples/prompts/patch-stdout.py) mentioned previously might work with the proxy. I've committed support for this to the [terminal-auth branch](https://github.com/simonrob/email-oauth2-proxy/tree/terminal-auth).

To use this feature you'll need to either update the proxy's requirements (`python -m pip install -r requirements-no-gui.txt`) or install prompt_toolkit: `python -m pip install prompt_toolkit`. Enable it by using the `--external-auth` flag in `--no-gui` mode.

Feedback very welcome!

**Comment by jlevon** [comment]
I know this is incredibly late, so no problem if not, but any chance that code is still around? Thanks.

**Comment by simonrob** [comment]
Yes - it was [merged into the proxy](https://github.com/simonrob/email-oauth2-proxy/commit/a26edc6e1370f399894059c1fe96beee666eda7a). You can find it when using the `--external-auth` option  in `--no-gui` mode (as long as `prompt_toolkit` is installed).

**Comment by jlevon** [comment]
Oops, didn't think to check - works great, thank you so much for adding this!

**Comment by simonrob** [comment]
Great! I'm glad this ended up being useful.

As an aside, this project gets a fair bit of traffic from [your blog post](https://movementarian.org/blog/posts/a-headless-office-365-proxy/), so it'd be nice if you could update it to note that this sort of headless usage is now supported.

**Comment by jlevon** [comment]
Done, thank you!

**Comment by simonrob** [comment]
Thanks!

(To answer the point in your post about why `delete_account_token_on_password_error = True` is the default – this is [explained](https://github.com/simonrob/email-oauth2-proxy/blob/73f7d8aa44d7404d9a7a3a6f7e9b3f6388c956fc/emailproxy.config#L199) in the sample config file. Long story short: several early issues were caused by the proxy *not* doing this, and people getting confused when using different IMAP/SMTP passwords. Having this as `True` means that rather than being seemingly locked out of one or the other protocol, they just get asked to authenticate repeatedly.)

**Comment by jlevon** [comment]
@simonrob I dialed down the rhetoric a little and corrected the link: I still don't really understand why token deletion is useful, but it's a moot point.

**Comment by simonrob** [comment]
No worries – I can see how it can be subjective, and also not appropriate in some situations, hence having the preference.

Thanks again for your post about the proxy – it's always nice to have external reviews/recommendations like this.
